auth_enabled: false

server:
  http_listen_port: 3100 # Grafana나 Pormtail이 로그를 보낼 때 사용
  grpc_listen_port: 9095 # gRPC 포트 명시 (내부 통신 최적화)


### 공통 설정: 반복되는 경로 설정을 한 번에 관리하는 곳 
common:
  path_prefix: /loki # 모든 데이터가 저장될 기본 루트 폴더 
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1 # 1개만 저장
  ring:
    kvstore:
      store: inmemory

### 데이터 구조 설정: 데이터를 어떤 방식으로 저장하고 인덱싱할지
schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb # 로그 데이터의 인덱싱 방식
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

### 제한 및 보관 정책: 권한과 데이터 수명 결정
limits_config:
  allow_structured_metadata: true
  retention_period: ${LOKI_RETENTION}

### 집행자: retention_period가 지나면 실제로 디스크에서 파일을 삭제하는 역할
compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m        # 삭제 및 압축 확인 주기
  retention_enabled: true         # 보관 주기 정책 활성화
  retention_delete_delay: 2h      # 삭제 대기 시간
  retention_delete_worker_count: 150 # 삭제 작업 처리량
  delete_request_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  ring:
    kvstore:
      store: inmemory
  enable_api: true
