stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  # Docker Hub 또는 GitLab Registry 주소
  IMAGE_FRONT: $DOCKER_USER/capsure-frontend
  IMAGE_BACK: $DOCKER_USER/capsure-backend
  IMAGE_MOCK: $DOCKER_USER/capsure-mydata-mock

# 모든 job에 공통으로 적용될 설정
before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

# [Stage 1] 빌드 단계: Runner(DevOps 서버)에서 이미지 생성 및 푸시
build-images:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # main 브랜치에 push(merge 포함)될 때만 실행
  script:
    - echo "Building for AWS (linux/amd64) and pushing to Docker Hub..."
    - docker buildx build --platform linux/amd64 -t $IMAGE_FRONT:latest ./Frontend --push
    - docker buildx build --platform linux/amd64 -t $IMAGE_BACK:latest ./Backend --push

### 테스트 빌드
build-images-test:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == " test"  # main 브랜치에 push(merge 포함)될 때만 실행
  script:
    - echo "Building for AWS (linux/amd64) and pushing to Docker Hub..."
    - docker buildx build --platform linux/amd64 -t $IMAGE_FRONT:test ./Frontend --push
    - docker buildx build --platform linux/amd64 -t $IMAGE_BACK:test ./Backend --push

deploy-to-aws:
  stage: deploy
  tags:
    - DevOps_and_Monitor
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    # SSH 접속을 위한 환경 설정 (GitLab Variables에 SSH_PRIVATE_KEY 등록 필요)
    - eval $(ssh-agent -s)
    # GitLab Variables에 등록된 개인키를 ssh-agent에 등록
    - echo "$MAIN_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Deploying to AWS Server..."

    - ssh -o StrictHostKeyChecking=no -p 22 ubuntu@$MAIN_AWS_HOST "mkdir -p /home/ubuntu/S14P21A308/Infra/main/"
    - scp -o StrictHostKeyChecking=no -P 22 ./Infra/main/* ubuntu@$MAIN_AWS_HOST:/home/ubuntu/S14P21A308/Infra/main/

    # SSH로 AWS 서버에 접속하여 명령 실행
    # MAIN_AWS_HOST(서버 IP)와 프로젝트 경로를 변수로 관리한다.
    - |
      ssh -o StrictHostKeyChecking=no -p 22 ubuntu@$MAIN_AWS_HOST "
        # 1. 대상 디렉토리로 이동
        cd /home/ubuntu/S14P21A308/Infra/main && \
        
        # 2. GitLab 변수를 기반으로 .env 파일 생성 및 내용 기입
        echo 'DOCKER_USER=$DOCKER_USER' > .env && \
        echo 'DATABASE_PASSWORD=$DB_PASSWORD' >> .env && \
        echo 'API_KEY=$SECRET_API_KEY' >> .env && \
        
        # 3. 파일 권한을 600(소유자 읽기/쓰기만 허용)으로 설정
        chmod 600 .env && \
        
        # 4. 최신 이미지 배포
        docker compose pull && \
        docker compose up -d
      "
    - |
      ssh -o StrictHostKeyChecking=no -p 22 ubuntu@$MAIN_AWS_HOST "
        export DOCKER_USER=$DOCKER_USER && \ 
        cd /home/ubuntu/S14P21A308/Infra/main && \ 
        docker compose pull && \ 
        docker compose up -d
      "

### Test 배포
deploy-test:
  stage: deploy
  tags:
    - DevOps_and_Monitor
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
  before_script:
    - eval $(ssh-agent -s)
    - echo "$MAIN_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Deploying Test to AWS..."
    - ssh -o StrictHostKeyChecking=no -p 22 ubuntu@$MAIN_AWS_HOST "mkdir -p /home/ubuntu/S14P21A308/Infra/main/test"
    - scp -o StrictHostKeyChecking=no -P 22 ./Infra/main/test/* ubuntu@$MAIN_AWS_HOST:/home/ubuntu/S14P21A308/Infra/main/test/
    - |
      ssh -o StrictHostKeyChecking=no -p 22 ubuntu@$MAIN_AWS_HOST "
        cd /home/ubuntu/S14P21A308/Infra/main/test && \
        echo 'DOCKER_USER=$DOCKER_USER' > .env && \
        docker compose pull && \
        docker compose up -d
      "