workflow:
  rules:
    # merge commit이 develop에 들어올 때만
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "test"'
      when: always
    - when: never

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_FRONT: $DOCKER_USER/capsure-frontend
  IMAGE_BACK: $DOCKER_USER/capsure-backend
  IMAGE_MOCK: $DOCKER_USER/capsure-mydata-mock

# 모든 job에 공통으로 적용될 설정
before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

# =========================
# BUILD Frontend
# =========================

# TODO: Frontend Prod

# =========================
# BUILD Frontend Test
# =========================

build-fe-test:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "test"  # main 브랜치에 push(merge 포함)될 때만 실행
  script:
    - echo "Building for AWS (linux/amd64) and pushing to Docker Hub..."
    - docker buildx build --platform linux/amd64 -t $IMAGE_FRONT:test ./Frontend --push

deploy-fe-test:
  stage: deploy
  tags:
    - DevOps_and_Monitor
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
    - changes:
        - Frontend/**/*
        - Infra/main/docker-compose.fe.test.yml
        - .gitlab-ci.yml
  script:
    - echo "Deploying Test to AWS..."
    # 1. 원격 서버 디렉토리 생성 및 설정 파일 복사
    - ssh -o StrictHostKeyChecking=no -p 22 ubuntu@$MAIN_AWS_HOST "mkdir -p /home/ubuntu/S14P21A308/Infra/main"
    - scp -o StrictHostKeyChecking=no -P 22 ./Infra/main/docker-compose.fe.test.yml ubuntu@$MAIN_AWS_HOST:/home/ubuntu/S14P21A308/Infra/main/
    
    # 2. 원격 서버 접속 후 일련의 명령 실행 (로그인 포함)
    - |
      ssh -o StrictHostKeyChecking=no -p 22 ubuntu@$MAIN_AWS_HOST "
        # Docker Hub 로그인 (AWS 서버 내부 인증)
        echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USER' --password-stdin && \
        
        cd /home/ubuntu/S14P21A308/Infra/main && \
        
        # .env 파일 생성 (필요한 변수 모두 기입)
        echo 'DOCKER_USER=$DOCKER_USER' > .env && \
        chmod 600 .env && \
        
        # 배포 프로세스
        docker compose -f docker-compose.fe.test.yml pull && \
        docker compose -f docker-compose.fe.test.yml up -d 
      "