services:
  loki:
    image: grafana/loki:3.6.7
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-data:/loki
      - ./conf/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:3.6.7
    container_name: monitor-promtail
    restart: always
    depends_on:
      - loki
    volumes:
      - /var/log:/var/log:ro
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./promtail-data:/tmp/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:v3.10.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    networks:
      - monitor-net
  
  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: monitor-node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.rootfs=/rootfs'
    networks:
      - monitor-net

  cadvisor:
    image: ghcr.io/google/cadvisor:0.56.2
    container_name: monitor-cadvisor
    restart: always
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/host/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:12.4.1
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
