-- External financial interface message journal for payment approval and inquiry.

CREATE TABLE public.ifc_financial_message (
    financial_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_name VARCHAR(100) NOT NULL,
    message_type VARCHAR(100) NOT NULL,
    direction VARCHAR(30) NOT NULL,
    correlation_id VARCHAR(200) NOT NULL,
    idempotency_key VARCHAR(150),
    business_key VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL,
    error_code VARCHAR(100),
    payload_json JSONB NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_ifc_financial_message_direction
        CHECK (direction IN ('OUTBOUND_REQUEST', 'INBOUND_RESPONSE')),
    CONSTRAINT chk_ifc_financial_message_status
        CHECK (status IN ('REQUESTED', 'SUCCEEDED', 'REJECTED', 'TIMEOUT', 'CIRCUIT_OPEN', 'ERROR')),
    CONSTRAINT chk_ifc_financial_message_hash
        CHECK (payload_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_ifc_financial_message_correlation
    ON public.ifc_financial_message (interface_name, correlation_id, financial_message_id);

CREATE INDEX ix_ifc_financial_message_business
    ON public.ifc_financial_message (business_key, occurred_at DESC, financial_message_id DESC);
