-- Recurring premium collection is intentionally separated from a payment order.
-- A customer can prepay while an automatic-debit instruction is already in-flight.

CREATE TABLE public.ins_premium_receivable (
    premium_receivable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL,
    billing_cycle DATE NOT NULL,
    due_date DATE NOT NULL,
    grace_ends_on DATE NOT NULL,
    amount_due NUMERIC(18, 2) NOT NULL,
    amount_settled NUMERIC(18, 2) NOT NULL DEFAULT 0,
    currency_code CHAR(3) NOT NULL DEFAULT 'KRW',
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_premium_receivable_policy
        FOREIGN KEY (policy_id) REFERENCES public.ins_policy (policy_id),
    CONSTRAINT uk_ins_premium_receivable_cycle UNIQUE (policy_id, billing_cycle),
    CONSTRAINT chk_ins_premium_receivable_amounts
        CHECK (amount_due > 0 AND amount_settled >= 0),
    CONSTRAINT chk_ins_premium_receivable_dates
        CHECK (grace_ends_on >= due_date),
    CONSTRAINT chk_ins_premium_receivable_status
        CHECK (status IN ('DUE', 'GRACE', 'SETTLED', 'OVERPAID', 'LAPSED'))
);

CREATE TABLE public.pay_collection_instruction (
    collection_instruction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premium_receivable_id BIGINT NOT NULL,
    instruction_no VARCHAR(100) NOT NULL,
    collection_method VARCHAR(30) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_request_key VARCHAR(200),
    idempotency_key VARCHAR(150) NOT NULL,
    status VARCHAR(30) NOT NULL,
    submitted_at TIMESTAMPTZ,
    captured_at TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_pay_collection_instruction_receivable
        FOREIGN KEY (premium_receivable_id) REFERENCES public.ins_premium_receivable (premium_receivable_id),
    CONSTRAINT uk_pay_collection_instruction_no UNIQUE (instruction_no),
    CONSTRAINT uk_pay_collection_instruction_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uk_pay_collection_provider_key UNIQUE (provider, provider_request_key),
    CONSTRAINT chk_pay_collection_instruction_amount CHECK (amount > 0),
    CONSTRAINT chk_pay_collection_instruction_method
        CHECK (collection_method IN ('AUTO_DEBIT', 'INSTANT_PAYMENT')),
    CONSTRAINT chk_pay_collection_instruction_status
        CHECK (status IN ('SCHEDULED', 'SUBMITTED', 'CANCEL_REQUESTED', 'CANCELED', 'CAPTURED', 'FAILED', 'UNKNOWN'))
);

CREATE TABLE public.pay_premium_settlement (
    premium_settlement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premium_receivable_id BIGINT NOT NULL,
    collection_instruction_id BIGINT NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    provider_transaction_key VARCHAR(200) NOT NULL,
    settled_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_pay_premium_settlement_receivable
        FOREIGN KEY (premium_receivable_id) REFERENCES public.ins_premium_receivable (premium_receivable_id),
    CONSTRAINT fk_pay_premium_settlement_instruction
        FOREIGN KEY (collection_instruction_id) REFERENCES public.pay_collection_instruction (collection_instruction_id),
    CONSTRAINT uk_pay_premium_settlement_provider_transaction UNIQUE (provider_transaction_key),
    CONSTRAINT chk_pay_premium_settlement_amount CHECK (amount > 0)
);

CREATE TABLE public.pay_refund_case (
    refund_case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premium_receivable_id BIGINT NOT NULL,
    refund_no VARCHAR(100) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    reason_code VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    reviewed_at TIMESTAMPTZ,
    refunded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_pay_refund_case_receivable
        FOREIGN KEY (premium_receivable_id) REFERENCES public.ins_premium_receivable (premium_receivable_id),
    CONSTRAINT uk_pay_refund_case_no UNIQUE (refund_no),
    CONSTRAINT uk_pay_refund_case_idempotency UNIQUE (idempotency_key),
    CONSTRAINT chk_pay_refund_case_amount CHECK (amount > 0),
    CONSTRAINT chk_pay_refund_case_status
        CHECK (status IN ('PENDING', 'AUTO_REFUND_ELIGIBLE', 'MANUAL_REVIEW', 'REFUNDED', 'FAILED'))
);

CREATE INDEX ix_ins_premium_receivable_collection
    ON public.ins_premium_receivable (status, due_date, grace_ends_on);

CREATE INDEX ix_pay_collection_instruction_batch
    ON public.pay_collection_instruction (status, created_at);

CREATE INDEX ix_pay_refund_case_queue
    ON public.pay_refund_case (status, created_at);
