-- Claim Review Copilot은 고객 원문이나 모델 출력 없이 검토 상태와 담당자 식별자만 영속화한다.
CREATE TABLE public.ops_claim_copilot_review (
    claim_copilot_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL REFERENCES public.clm_claim(claim_id) ON DELETE CASCADE,
    request_id VARCHAR(100) NOT NULL,
    review_status VARCHAR(20) NOT NULL CHECK (review_status IN ('DRAFT', 'CONFIRMED', 'REJECTED')),
    reviewer_user_id BIGINT REFERENCES public.usr_user(user_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_ops_claim_copilot_review_claim_request UNIQUE (claim_id, request_id)
);

CREATE INDEX ix_ops_claim_copilot_review_claim_updated
    ON public.ops_claim_copilot_review (claim_id, updated_at DESC);
