-- 상태 변경 이력은 append-only로 남기고, 고객 원문·프롬프트·모델 출력은 보관하지 않는다.
CREATE TABLE public.ops_claim_copilot_review_event (
    claim_copilot_review_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL,
    request_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(30) NOT NULL CHECK (event_type IN ('DRAFT_CREATED', 'REVIEW_CONFIRMED', 'REVIEW_REJECTED')),
    review_status VARCHAR(20) NOT NULL CHECK (review_status IN ('DRAFT', 'CONFIRMED', 'REJECTED')),
    reviewer_user_id BIGINT REFERENCES public.usr_user(user_id) ON DELETE SET NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ops_claim_copilot_review_event_review
        FOREIGN KEY (claim_id, request_id)
        REFERENCES public.ops_claim_copilot_review (claim_id, request_id)
        ON DELETE CASCADE
);

CREATE INDEX ix_ops_claim_copilot_review_event_review
    ON public.ops_claim_copilot_review_event (claim_id, request_id, claim_copilot_review_event_id);
