-- CapSure 교육용 암보험 금융 프로세스의 additive schema.
-- 기존 subscription/product_source 구조를 삭제하거나 변경하지 않는다.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- Catalog and terms
-- ---------------------------------------------------------------------------
CREATE TABLE public.ins_terms_document (
    terms_document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code VARCHAR(100) NOT NULL,
    document_version VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_uri VARCHAR(512),
    source_hash CHAR(64) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    status VARCHAR(30) NOT NULL,
    is_simulation BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_ins_terms_document_version UNIQUE (document_code, document_version),
    CONSTRAINT chk_ins_terms_document_hash CHECK (source_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_ins_terms_document_period CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT chk_ins_terms_document_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'RETIRED'))
);

CREATE TABLE public.ins_terms_clause (
    terms_clause_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terms_document_id BIGINT NOT NULL,
    clause_code VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    page_no INTEGER,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_terms_clause_document
        FOREIGN KEY (terms_document_id) REFERENCES public.ins_terms_document (terms_document_id),
    CONSTRAINT uk_ins_terms_clause_code UNIQUE (terms_document_id, clause_code),
    CONSTRAINT chk_ins_terms_clause_page CHECK (page_no IS NULL OR page_no > 0),
    CONSTRAINT chk_ins_terms_clause_sort CHECK (sort_order > 0)
);

CREATE TABLE public.ins_product_version (
    product_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(100) NOT NULL,
    version VARCHAR(50) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    insurer_name VARCHAR(255) NOT NULL,
    insurer_sector VARCHAR(20) NOT NULL,
    sale_from DATE NOT NULL,
    sale_to DATE,
    status VARCHAR(30) NOT NULL,
    base_monthly_premium NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'KRW',
    terms_document_id BIGINT NOT NULL,
    is_simulation BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_product_version_terms
        FOREIGN KEY (terms_document_id) REFERENCES public.ins_terms_document (terms_document_id),
    CONSTRAINT uk_ins_product_version UNIQUE (product_code, version),
    CONSTRAINT chk_ins_product_version_sale_period CHECK (sale_to IS NULL OR sale_to >= sale_from),
    CONSTRAINT chk_ins_product_version_status CHECK (status IN ('DRAFT', 'ON_SALE', 'SUSPENDED', 'CLOSED')),
    CONSTRAINT chk_ins_product_version_sector CHECK (insurer_sector IN ('LIFE', 'NONLIFE', 'THIRD_INSURANCE')),
    CONSTRAINT chk_ins_product_version_premium CHECK (base_monthly_premium >= 0)
);

CREATE TABLE public.ins_coverage (
    coverage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coverage_code VARCHAR(100) NOT NULL,
    coverage_name VARCHAR(255) NOT NULL,
    coverage_category VARCHAR(50) NOT NULL,
    benefit_type VARCHAR(30) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_ins_coverage_code UNIQUE (coverage_code),
    CONSTRAINT chk_ins_coverage_benefit_type CHECK (benefit_type IN ('FIXED_BENEFIT', 'INDEMNITY'))
);

CREATE TABLE public.ins_product_coverage (
    product_coverage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_version_id BIGINT NOT NULL,
    coverage_id BIGINT NOT NULL,
    insured_amount NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'KRW',
    waiting_period_days INTEGER NOT NULL DEFAULT 0,
    reduction_period_days INTEGER NOT NULL DEFAULT 0,
    reduction_rate NUMERIC(5, 4) NOT NULL DEFAULT 1.0000,
    coverage_start_rule VARCHAR(50) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_product_coverage_product
        FOREIGN KEY (product_version_id) REFERENCES public.ins_product_version (product_version_id),
    CONSTRAINT fk_ins_product_coverage_coverage
        FOREIGN KEY (coverage_id) REFERENCES public.ins_coverage (coverage_id),
    CONSTRAINT uk_ins_product_coverage UNIQUE (product_version_id, coverage_id),
    CONSTRAINT chk_ins_product_coverage_amount CHECK (insured_amount >= 0),
    CONSTRAINT chk_ins_product_coverage_period CHECK (waiting_period_days >= 0 AND reduction_period_days >= 0),
    CONSTRAINT chk_ins_product_coverage_rate CHECK (reduction_rate > 0 AND reduction_rate <= 1),
    CONSTRAINT chk_ins_product_coverage_order CHECK (display_order > 0)
);

CREATE TABLE public.ins_coverage_rule (
    coverage_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_coverage_id BIGINT NOT NULL,
    rule_version VARCHAR(50) NOT NULL,
    rule_type VARCHAR(50) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 100,
    rule_json JSONB NOT NULL,
    terms_clause_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_coverage_rule_product_coverage
        FOREIGN KEY (product_coverage_id) REFERENCES public.ins_product_coverage (product_coverage_id),
    CONSTRAINT fk_ins_coverage_rule_clause
        FOREIGN KEY (terms_clause_id) REFERENCES public.ins_terms_clause (terms_clause_id),
    CONSTRAINT uk_ins_coverage_rule UNIQUE (product_coverage_id, rule_version, rule_type),
    CONSTRAINT chk_ins_coverage_rule_priority CHECK (priority >= 0)
);

-- ---------------------------------------------------------------------------
-- Quote, application and underwriting
-- ---------------------------------------------------------------------------
CREATE TABLE public.ins_quote (
    quote_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_no VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    product_version_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    monthly_premium NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'KRW',
    snapshot_json JSONB NOT NULL,
    terms_document_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_quote_user
        FOREIGN KEY (user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT fk_ins_quote_product
        FOREIGN KEY (product_version_id) REFERENCES public.ins_product_version (product_version_id),
    CONSTRAINT uk_ins_quote_no UNIQUE (quote_no),
    CONSTRAINT chk_ins_quote_status CHECK (status IN ('DRAFT', 'ISSUED', 'USED', 'EXPIRED', 'CANCELED')),
    CONSTRAINT chk_ins_quote_premium CHECK (monthly_premium >= 0),
    CONSTRAINT chk_ins_quote_hash CHECK (terms_document_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE public.ins_application (
    application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no VARCHAR(100) NOT NULL,
    quote_id BIGINT NOT NULL,
    applicant_user_id BIGINT NOT NULL,
    insured_user_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    disclosure_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    submitted_at TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_application_quote
        FOREIGN KEY (quote_id) REFERENCES public.ins_quote (quote_id),
    CONSTRAINT fk_ins_application_applicant
        FOREIGN KEY (applicant_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT fk_ins_application_insured
        FOREIGN KEY (insured_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT uk_ins_application_no UNIQUE (application_no),
    CONSTRAINT uk_ins_application_quote UNIQUE (quote_id),
    CONSTRAINT chk_ins_application_status CHECK (
        status IN ('DRAFT', 'DISCLOSURE_COMPLETED', 'SUBMITTED', 'UNDER_REVIEW',
                   'APPROVED', 'MANUAL_REVIEW', 'DECLINED', 'WITHDRAWN')
    )
);

CREATE TABLE public.ins_consent (
    consent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    consent_type VARCHAR(50) NOT NULL,
    terms_document_id BIGINT NOT NULL,
    document_hash CHAR(64) NOT NULL,
    is_required BOOLEAN NOT NULL,
    agreed BOOLEAN NOT NULL,
    actor_user_id BIGINT NOT NULL,
    agreed_at TIMESTAMPTZ,
    request_id VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_consent_application
        FOREIGN KEY (application_id) REFERENCES public.ins_application (application_id),
    CONSTRAINT fk_ins_consent_terms
        FOREIGN KEY (terms_document_id) REFERENCES public.ins_terms_document (terms_document_id),
    CONSTRAINT fk_ins_consent_actor
        FOREIGN KEY (actor_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT uk_ins_consent_type UNIQUE (application_id, consent_type),
    CONSTRAINT chk_ins_consent_hash CHECK (document_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_ins_consent_agreed_at CHECK ((agreed AND agreed_at IS NOT NULL) OR NOT agreed)
);

CREATE TABLE public.ins_uw_decision (
    underwriting_decision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    decision_version INTEGER NOT NULL,
    decision VARCHAR(30) NOT NULL,
    rule_version VARCHAR(50) NOT NULL,
    reason_codes_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    input_hash CHAR(64) NOT NULL,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_uw_decision_application
        FOREIGN KEY (application_id) REFERENCES public.ins_application (application_id),
    CONSTRAINT uk_ins_uw_decision_version UNIQUE (application_id, decision_version),
    CONSTRAINT chk_ins_uw_decision CHECK (decision IN ('APPROVED', 'MANUAL_REVIEW', 'DECLINED')),
    CONSTRAINT chk_ins_uw_decision_version CHECK (decision_version > 0),
    CONSTRAINT chk_ins_uw_decision_hash CHECK (input_hash ~ '^[0-9a-f]{64}$')
);

-- ---------------------------------------------------------------------------
-- Policy
-- ---------------------------------------------------------------------------
CREATE TABLE public.ins_policy (
    policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_no VARCHAR(100) NOT NULL,
    application_id BIGINT NOT NULL,
    policyholder_user_id BIGINT NOT NULL,
    insured_user_id BIGINT NOT NULL,
    beneficiary_user_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    activated_at TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    lapsed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_policy_application
        FOREIGN KEY (application_id) REFERENCES public.ins_application (application_id),
    CONSTRAINT fk_ins_policy_policyholder
        FOREIGN KEY (policyholder_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT fk_ins_policy_insured
        FOREIGN KEY (insured_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT fk_ins_policy_beneficiary
        FOREIGN KEY (beneficiary_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT uk_ins_policy_no UNIQUE (policy_no),
    CONSTRAINT uk_ins_policy_application UNIQUE (application_id),
    CONSTRAINT chk_ins_policy_status CHECK (
        status IN ('PENDING_INITIAL_PREMIUM', 'ACTIVE', 'GRACE', 'CHANGE_SCHEDULED',
                   'CANCELED', 'LAPSED', 'EXPIRED')
    ),
    CONSTRAINT chk_ins_policy_activation CHECK (status <> 'ACTIVE' OR activated_at IS NOT NULL)
);

CREATE TABLE public.ins_policy_version (
    policy_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    product_version_id BIGINT NOT NULL,
    terms_document_id BIGINT NOT NULL,
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    snapshot_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_policy_version_policy
        FOREIGN KEY (policy_id) REFERENCES public.ins_policy (policy_id),
    CONSTRAINT fk_ins_policy_version_product
        FOREIGN KEY (product_version_id) REFERENCES public.ins_product_version (product_version_id),
    CONSTRAINT fk_ins_policy_version_terms
        FOREIGN KEY (terms_document_id) REFERENCES public.ins_terms_document (terms_document_id),
    CONSTRAINT uk_ins_policy_version UNIQUE (policy_id, version),
    CONSTRAINT chk_ins_policy_version_number CHECK (version > 0),
    CONSTRAINT chk_ins_policy_version_period CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE TABLE public.ins_policy_coverage (
    policy_coverage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version_id BIGINT NOT NULL,
    product_coverage_id BIGINT NOT NULL,
    coverage_code_snapshot VARCHAR(100) NOT NULL,
    insured_amount NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'KRW',
    coverage_start_at TIMESTAMPTZ NOT NULL,
    coverage_end_at TIMESTAMPTZ,
    paid_benefit_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ins_policy_coverage_version
        FOREIGN KEY (policy_version_id) REFERENCES public.ins_policy_version (policy_version_id),
    CONSTRAINT fk_ins_policy_coverage_product
        FOREIGN KEY (product_coverage_id) REFERENCES public.ins_product_coverage (product_coverage_id),
    CONSTRAINT uk_ins_policy_coverage UNIQUE (policy_version_id, product_coverage_id),
    CONSTRAINT chk_ins_policy_coverage_amount CHECK (insured_amount >= 0),
    CONSTRAINT chk_ins_policy_coverage_period CHECK (coverage_end_at IS NULL OR coverage_end_at > coverage_start_at),
    CONSTRAINT chk_ins_policy_coverage_paid_count CHECK (paid_benefit_count >= 0)
);

-- ---------------------------------------------------------------------------
-- Premium payment
-- ---------------------------------------------------------------------------
CREATE TABLE public.pay_order (
    payment_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(100) NOT NULL,
    business_key VARCHAR(150) NOT NULL,
    application_id BIGINT NOT NULL,
    policy_id BIGINT,
    purpose VARCHAR(40) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'KRW',
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    expires_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_pay_order_application
        FOREIGN KEY (application_id) REFERENCES public.ins_application (application_id),
    CONSTRAINT fk_pay_order_policy
        FOREIGN KEY (policy_id) REFERENCES public.ins_policy (policy_id),
    CONSTRAINT uk_pay_order_no UNIQUE (order_no),
    CONSTRAINT uk_pay_order_business UNIQUE (business_key),
    CONSTRAINT uk_pay_order_idempotency UNIQUE (idempotency_key),
    CONSTRAINT chk_pay_order_purpose CHECK (purpose IN ('INITIAL_PREMIUM', 'RECURRING_PREMIUM')),
    CONSTRAINT chk_pay_order_amount CHECK (amount >= 0),
    CONSTRAINT chk_pay_order_status CHECK (
        status IN ('CREATED', 'AUTHENTICATED', 'APPROVING', 'PAID', 'FAILED', 'EXPIRED',
                   'UNKNOWN', 'CANCEL_PENDING', 'CANCELED', 'PARTIALLY_CANCELED')
    ),
    CONSTRAINT chk_pay_order_paid_at CHECK (status <> 'PAID' OR paid_at IS NOT NULL)
);

CREATE TABLE public.pay_attempt (
    payment_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id BIGINT NOT NULL,
    attempt_no INTEGER NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_payment_key VARCHAR(200),
    idempotency_key VARCHAR(150) NOT NULL,
    status VARCHAR(30) NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    request_json JSONB,
    response_json JSONB,
    error_code VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_pay_attempt_order
        FOREIGN KEY (payment_order_id) REFERENCES public.pay_order (payment_order_id),
    CONSTRAINT uk_pay_attempt_number UNIQUE (payment_order_id, attempt_no),
    CONSTRAINT uk_pay_attempt_idempotency UNIQUE (idempotency_key),
    CONSTRAINT chk_pay_attempt_number CHECK (attempt_no > 0),
    CONSTRAINT chk_pay_attempt_status CHECK (
        status IN ('CREATED', 'PROCESSING', 'PAID', 'FAILED', 'UNKNOWN', 'CANCELED')
    )
);

CREATE TABLE public.pay_webhook_event (
    payment_webhook_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(30) NOT NULL,
    provider_event_id VARCHAR(200) NOT NULL,
    provider_payment_key VARCHAR(200),
    event_type VARCHAR(100) NOT NULL,
    payload_json JSONB NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    processing_status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    error_reason TEXT,
    CONSTRAINT uk_pay_webhook_provider_event UNIQUE (provider, provider_event_id),
    CONSTRAINT chk_pay_webhook_hash CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_pay_webhook_status CHECK (processing_status IN ('RECEIVED', 'PROCESSED', 'DUPLICATE', 'FAILED'))
);

-- ---------------------------------------------------------------------------
-- Claim assessment and simulated payout
-- ---------------------------------------------------------------------------
CREATE TABLE public.clm_claim (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_no VARCHAR(100) NOT NULL,
    policy_id BIGINT NOT NULL,
    policy_coverage_id BIGINT NOT NULL,
    claimant_user_id BIGINT NOT NULL,
    incident_at TIMESTAMPTZ NOT NULL,
    event_fingerprint CHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    submitted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_clm_claim_policy
        FOREIGN KEY (policy_id) REFERENCES public.ins_policy (policy_id),
    CONSTRAINT fk_clm_claim_coverage
        FOREIGN KEY (policy_coverage_id) REFERENCES public.ins_policy_coverage (policy_coverage_id),
    CONSTRAINT fk_clm_claim_claimant
        FOREIGN KEY (claimant_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT uk_clm_claim_no UNIQUE (claim_no),
    CONSTRAINT uk_clm_claim_event UNIQUE (policy_coverage_id, event_fingerprint),
    CONSTRAINT chk_clm_claim_fingerprint CHECK (event_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_clm_claim_status CHECK (
        status IN ('DRAFT', 'DOCUMENTS_PENDING', 'SUBMITTED', 'ASSESSING',
                   'APPROVED', 'MANUAL_REVIEW', 'DENIED', 'PAYMENT_SCHEDULED',
                   'PAID', 'PAYMENT_FAILED')
    )
);

CREATE TABLE public.clm_evidence (
    claim_evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL,
    evidence_type VARCHAR(50) NOT NULL,
    synthetic_reference VARCHAR(255) NOT NULL,
    checksum CHAR(64) NOT NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_clm_evidence_claim
        FOREIGN KEY (claim_id) REFERENCES public.clm_claim (claim_id),
    CONSTRAINT uk_clm_evidence UNIQUE (claim_id, evidence_type, checksum),
    CONSTRAINT chk_clm_evidence_checksum CHECK (checksum ~ '^[0-9a-f]{64}$')
);

CREATE TABLE public.clm_decision (
    claim_decision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL,
    decision_version INTEGER NOT NULL,
    result VARCHAR(30) NOT NULL,
    benefit_amount NUMERIC(18, 2),
    currency_code CHAR(3) NOT NULL DEFAULT 'KRW',
    reason_codes_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    terms_clause_id BIGINT NOT NULL,
    rule_version VARCHAR(50) NOT NULL,
    input_hash CHAR(64) NOT NULL,
    actor_type VARCHAR(30) NOT NULL,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_clm_decision_claim
        FOREIGN KEY (claim_id) REFERENCES public.clm_claim (claim_id),
    CONSTRAINT fk_clm_decision_clause
        FOREIGN KEY (terms_clause_id) REFERENCES public.ins_terms_clause (terms_clause_id),
    CONSTRAINT uk_clm_decision_version UNIQUE (claim_id, decision_version),
    CONSTRAINT chk_clm_decision_version CHECK (decision_version > 0),
    CONSTRAINT chk_clm_decision_result CHECK (result IN ('APPROVED', 'MANUAL_REVIEW', 'DENIED')),
    CONSTRAINT chk_clm_decision_amount CHECK (
        (result = 'APPROVED' AND benefit_amount IS NOT NULL AND benefit_amount >= 0)
        OR (result <> 'APPROVED' AND benefit_amount IS NULL)
    ),
    CONSTRAINT chk_clm_decision_hash CHECK (input_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_clm_decision_actor CHECK (actor_type IN ('RULE_ENGINE', 'CLAIM_EXAMINER'))
);

CREATE TABLE public.clm_payment (
    claim_payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_decision_id BIGINT NOT NULL,
    payout_order_no VARCHAR(100) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'KRW',
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_clm_payment_decision
        FOREIGN KEY (claim_decision_id) REFERENCES public.clm_decision (claim_decision_id),
    CONSTRAINT uk_clm_payment_decision UNIQUE (claim_decision_id),
    CONSTRAINT uk_clm_payment_order UNIQUE (payout_order_no),
    CONSTRAINT uk_clm_payment_idempotency UNIQUE (idempotency_key),
    CONSTRAINT chk_clm_payment_amount CHECK (amount >= 0),
    CONSTRAINT chk_clm_payment_status CHECK (status IN ('SCHEDULED', 'PROCESSING', 'PAID', 'FAILED')),
    CONSTRAINT chk_clm_payment_paid_at CHECK (status <> 'PAID' OR paid_at IS NOT NULL)
);

-- ---------------------------------------------------------------------------
-- Operations, outbox and reconciliation
-- ---------------------------------------------------------------------------
CREATE TABLE public.ops_outbox_event (
    outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    locked_at TIMESTAMPTZ,
    locked_by VARCHAR(100),
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_ops_outbox_event_id UNIQUE (event_id),
    CONSTRAINT chk_ops_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED', 'DEAD_LETTER')),
    CONSTRAINT chk_ops_outbox_attempt_count CHECK (attempt_count >= 0)
);

CREATE TABLE public.ops_outbox_dead_letter (
    dead_letter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    payload_json JSONB NOT NULL,
    error_reason TEXT NOT NULL,
    replay_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    replay_actor_user_id BIGINT,
    replayed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ops_outbox_dlq_actor
        FOREIGN KEY (replay_actor_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT chk_ops_outbox_dlq_status CHECK (replay_status IN ('PENDING', 'REPLAYED', 'DISCARDED'))
);

CREATE TABLE public.ops_reconciliation (
    reconciliation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    local_status VARCHAR(50) NOT NULL,
    provider_status VARCHAR(50) NOT NULL,
    result VARCHAR(30) NOT NULL,
    details_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_ops_reconciliation_result CHECK (result IN ('MATCHED', 'CORRECTED', 'STILL_UNKNOWN', 'FAILED'))
);

CREATE TABLE public.ops_job_execution (
    job_execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    instance_key VARCHAR(255) NOT NULL,
    execution_no INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    checkpoint_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    input_count BIGINT NOT NULL DEFAULT 0,
    accepted_count BIGINT NOT NULL DEFAULT 0,
    duplicate_count BIGINT NOT NULL DEFAULT 0,
    quarantined_count BIGINT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    error_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_ops_job_execution UNIQUE (job_name, instance_key, execution_no),
    CONSTRAINT chk_ops_job_execution_no CHECK (execution_no > 0),
    CONSTRAINT chk_ops_job_status CHECK (status IN ('STARTING', 'RUNNING', 'COMPLETED', 'FAILED', 'STOPPED')),
    CONSTRAINT chk_ops_job_counts CHECK (
        input_count >= 0 AND accepted_count >= 0 AND duplicate_count >= 0 AND quarantined_count >= 0
    )
);

CREATE TABLE public.ops_quarantine (
    quarantine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_execution_id BIGINT NOT NULL,
    source_key VARCHAR(255) NOT NULL,
    reason_code VARCHAR(100) NOT NULL,
    raw_hash CHAR(64) NOT NULL,
    raw_payload_json JSONB NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ops_quarantine_execution
        FOREIGN KEY (job_execution_id) REFERENCES public.ops_job_execution (job_execution_id),
    CONSTRAINT uk_ops_quarantine_source UNIQUE (job_execution_id, source_key),
    CONSTRAINT chk_ops_quarantine_hash CHECK (raw_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_ops_quarantine_status CHECK (status IN ('PENDING', 'RESOLVED', 'IGNORED'))
);

-- ---------------------------------------------------------------------------
-- Indexes used by channel reads and workers
-- ---------------------------------------------------------------------------
CREATE INDEX ix_ins_product_version_sale
    ON public.ins_product_version (status, sale_from, sale_to);
CREATE INDEX ix_ins_terms_clause_document_order
    ON public.ins_terms_clause (terms_document_id, sort_order);
CREATE INDEX ix_ins_application_user_status
    ON public.ins_application (applicant_user_id, status, application_id DESC);
CREATE INDEX ix_ins_policy_user_status
    ON public.ins_policy (policyholder_user_id, status, policy_id DESC);
CREATE INDEX ix_ins_policy_coverage_incident_lookup
    ON public.ins_policy_coverage (policy_version_id, coverage_start_at, coverage_end_at);
CREATE INDEX ix_pay_order_reconciliation
    ON public.pay_order (status, updated_at)
    WHERE status IN ('APPROVING', 'UNKNOWN');
CREATE INDEX ix_pay_attempt_order
    ON public.pay_attempt (payment_order_id, attempt_no DESC);
CREATE INDEX ix_pay_webhook_processing
    ON public.pay_webhook_event (processing_status, received_at);
CREATE INDEX ix_clm_claim_policy_status
    ON public.clm_claim (policy_id, status, claim_id DESC);
CREATE INDEX ix_ops_outbox_worker
    ON public.ops_outbox_event (status, available_at, outbox_event_id);
CREATE INDEX ix_ops_job_execution_instance
    ON public.ops_job_execution (job_name, instance_key, execution_no DESC);
CREATE INDEX ix_ops_quarantine_status
    ON public.ops_quarantine (status, quarantine_id);

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
CREATE TRIGGER trg_ins_application_set_updated_at
BEFORE UPDATE ON public.ins_application
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_ins_policy_set_updated_at
BEFORE UPDATE ON public.ins_policy
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_pay_order_set_updated_at
BEFORE UPDATE ON public.pay_order
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_pay_attempt_set_updated_at
BEFORE UPDATE ON public.pay_attempt
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_clm_claim_set_updated_at
BEFORE UPDATE ON public.clm_claim
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_clm_payment_set_updated_at
BEFORE UPDATE ON public.clm_payment
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_ops_outbox_set_updated_at
BEFORE UPDATE ON public.ops_outbox_event
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_ops_job_execution_set_updated_at
BEFORE UPDATE ON public.ops_job_execution
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
