-- 상품·약관 버전을 신규 판매 경로에 노출하기 전에 관리자 승인을 요구한다.
-- 기존 운영 중인 버전은 호환성을 위해 승인 상태로 이관하고, 이후 생성 버전의 기본값은 승인 대기로 둔다.

ALTER TABLE public.ins_product_version
    ADD COLUMN release_status VARCHAR(30) NOT NULL DEFAULT 'APPROVED';

ALTER TABLE public.ins_product_version
    ALTER COLUMN release_status SET DEFAULT 'PENDING_APPROVAL';

ALTER TABLE public.ins_product_version
    ADD CONSTRAINT chk_ins_product_version_release_status
        CHECK (release_status IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED'));

CREATE TABLE public.ops_product_version_approval_event (
    approval_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_version_id BIGINT NOT NULL,
    product_code_snapshot VARCHAR(100) NOT NULL,
    product_version_snapshot VARCHAR(50) NOT NULL,
    terms_document_id BIGINT NOT NULL,
    terms_version_snapshot VARCHAR(50) NOT NULL,
    decision VARCHAR(20) NOT NULL,
    previous_status VARCHAR(30) NOT NULL,
    resulting_status VARCHAR(30) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    decided_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ops_product_version_approval_product
        FOREIGN KEY (product_version_id) REFERENCES public.ins_product_version (product_version_id),
    CONSTRAINT fk_ops_product_version_approval_terms
        FOREIGN KEY (terms_document_id) REFERENCES public.ins_terms_document (terms_document_id),
    CONSTRAINT fk_ops_product_version_approval_actor
        FOREIGN KEY (actor_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT uk_ops_product_version_approval_terminal
        UNIQUE (product_version_id),
    CONSTRAINT chk_ops_product_version_approval_decision
        CHECK (decision IN ('APPROVE', 'REJECT')),
    CONSTRAINT chk_ops_product_version_approval_transition
        CHECK (
            previous_status = 'PENDING_APPROVAL'
            AND (
                (decision = 'APPROVE' AND resulting_status = 'APPROVED')
                OR (decision = 'REJECT' AND resulting_status = 'REJECTED')
            )
        ),
    CONSTRAINT chk_ops_product_version_approval_reason
        CHECK (LENGTH(BTRIM(reason)) BETWEEN 1 AND 500)
);

CREATE INDEX ix_ops_product_version_approval_recent
    ON public.ops_product_version_approval_event (decided_at DESC, approval_event_id DESC);

