-- 청구 상세·증빙 조회는 원문이나 민감 메타데이터 없이 접근 주체와 결과만 append-only로 남긴다.
CREATE TABLE public.ops_claim_evidence_access_event (
    access_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_request_id UUID NOT NULL,
    actor_user_id BIGINT NOT NULL,
    claim_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT NOT NULL,
    access_action VARCHAR(30) NOT NULL,
    access_result VARCHAR(30) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_ops_claim_evidence_access_target
        UNIQUE (access_request_id, target_type, target_id),
    CONSTRAINT chk_ops_claim_evidence_access_target
        CHECK (target_type IN ('CLAIM', 'EVIDENCE')),
    CONSTRAINT chk_ops_claim_evidence_access_action
        CHECK (access_action = 'CLAIM_DETAIL_READ'),
    CONSTRAINT chk_ops_claim_evidence_access_result
        CHECK (access_result IN ('ALLOWED', 'DENIED_NOT_FOUND')),
    CONSTRAINT chk_ops_claim_evidence_access_claim_target
        CHECK (target_type <> 'CLAIM' OR target_id = claim_id),
    CONSTRAINT chk_ops_claim_evidence_access_denied_target
        CHECK (access_result <> 'DENIED_NOT_FOUND' OR target_type = 'CLAIM')
);

CREATE INDEX ix_ops_claim_evidence_access_actor_recent
    ON public.ops_claim_evidence_access_event (actor_user_id, occurred_at DESC, access_event_id DESC);

CREATE INDEX ix_ops_claim_evidence_access_claim_recent
    ON public.ops_claim_evidence_access_event (claim_id, occurred_at DESC, access_event_id DESC);

CREATE OR REPLACE FUNCTION public.reject_claim_evidence_access_event_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'ops_claim_evidence_access_event is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_ops_claim_evidence_access_event_append_only
    BEFORE UPDATE OR DELETE ON public.ops_claim_evidence_access_event
    FOR EACH ROW
    EXECUTE FUNCTION public.reject_claim_evidence_access_event_change();
