-- Financial outbox relay read model and replay evidence.

ALTER TABLE public.ops_outbox_dead_letter
    ADD COLUMN replay_reason TEXT;

CREATE UNIQUE INDEX uk_ops_outbox_dead_letter_event
    ON public.ops_outbox_dead_letter (event_id);

CREATE TABLE public.ops_financial_event_audit (
    financial_event_audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    policy_id BIGINT,
    payload_json JSONB NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    projected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_ops_financial_event_audit_event UNIQUE (event_id),
    CONSTRAINT fk_ops_financial_event_audit_policy
        FOREIGN KEY (policy_id) REFERENCES public.ins_policy (policy_id),
    CONSTRAINT chk_ops_financial_event_audit_hash
        CHECK (payload_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_ops_financial_event_audit_policy
    ON public.ops_financial_event_audit (policy_id, occurred_at, financial_event_audit_id);

CREATE INDEX ix_ops_financial_event_audit_aggregate
    ON public.ops_financial_event_audit (aggregate_type, aggregate_id, occurred_at);
