-- 관리자 수동 복구 조치와 장애 복구 시간을 변경 불가 운영 원장으로 남긴다.

CREATE TABLE public.ops_recovery_action (
    recovery_action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR(50) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(255),
    actor_user_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    action_duration_ms BIGINT,
    recovery_time_ms BIGINT,
    result_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ops_recovery_action_actor
        FOREIGN KEY (actor_user_id) REFERENCES public.usr_user (user_id),
    CONSTRAINT chk_ops_recovery_action_type
        CHECK (action_type IN ('DLQ_REPLAY', 'PAYMENT_RECONCILIATION')),
    CONSTRAINT chk_ops_recovery_action_status
        CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT chk_ops_recovery_action_reason
        CHECK (LENGTH(BTRIM(reason)) BETWEEN 1 AND 500),
    CONSTRAINT chk_ops_recovery_action_time_order
        CHECK (started_at >= detected_at AND (completed_at IS NULL OR completed_at >= started_at)),
    CONSTRAINT chk_ops_recovery_action_durations
        CHECK (
            (status = 'RUNNING'
                AND completed_at IS NULL
                AND action_duration_ms IS NULL
                AND recovery_time_ms IS NULL)
            OR
            (status IN ('SUCCEEDED', 'FAILED')
                AND completed_at IS NOT NULL
                AND action_duration_ms >= 0
                AND recovery_time_ms >= action_duration_ms)
        )
);

CREATE INDEX ix_ops_recovery_action_recent
    ON public.ops_recovery_action (started_at DESC, recovery_action_id DESC);

CREATE INDEX ix_ops_recovery_action_target
    ON public.ops_recovery_action (target_type, target_id, recovery_action_id DESC);
