services:
  # [Test] Frontend
  frontend-test:
    image: ${DOCKER_USER}/capsure-frontend:test
    container_name: capsure-frontend-test
    ports:
      - "40080:40080" # FE 테스트용 포트
      - "40443:40443"
<<<<<<< HEAD
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
=======
>>>>>>> f2f456b ([Infra] 94 chore: 포트 번호 정리)
    restart: always
    environment:
      - NODE_ENV=development

  # [Test] Backend
  backend-test:
    image: ${DOCKER_USER}/capsure-backend:test
    container_name: capsure-backend-test
    ports:
      - "48000:48000"
    restart: always
    environment:
      - NODE_ENV=development