services:
  # [Test] Frontend
  frontend-test:
    image: ${DOCKER_USER}/capsure-frontend:test
    container_name: capsure-frontend-test
    ports:
      - "8080:80" # FE 테스트용 포트 : 8080
    restart: always
    environment:
      - NODE_ENV=development

  # [Test] Backend
  backend-test:
    image: ${DOCKER_USER}/capsure-backend:test
    container_name: capsure-backend-test
    ports:
      - "18000:8000"
    restart: always
    environment:
      - NODE_ENV=development