services:
  # [Production] Mock
  mock:
    image: ${DOCKER_USER}/mydata-mock:latest
    container_name: mydata-mock-prod
    ports:
      - "8000:8000"
    restart: always
    environment:
      - NODE_ENV=production