DROP TABLE IF EXISTS usr_user;
CREATE TABLE usr_user (
    user_id BIGSERIAL PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    password_encrypted VARCHAR(255) NULL,
    name VARCHAR(10) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    birth_date DATE NULL,
    gender VARCHAR(10) DEFAULT 'UNKNOWN' NULL,
    user_status VARCHAR(20) DEFAULT 'PENDING_ONBOARDING' NOT NULL,
    onboarding_completed_at TIMESTAMPTZ NULL,
    withdrawn_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);
